// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)

// import OldModalController from "./old_modal_controller"
// application.register("old-modal", OldModalController)

// import OldNavbarController from "./old_navbar_controller"
// application.register("old-navbar", OldNavbarController)