development:
  auth0_domain: dev-16gha0bzy8a8u2pq.eu.auth0.com
  auth0_client_id: 4cezfgSoJjUGGYEc5L3qBS6Y50wh2x9Q
  auth0_client_secret: emV4P7tGFfCUExcoPgaPAHjvVC91kJOP2YbLS30hCJsEvsSqYvNkFPTfPPb6P9Zu